### ISSUE TITLE
AR support

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#105]
1. Should we support AR, too? In the same extension? Or the separated extension?
2. If we do, how? (UI, technical stuffs, and so on) We need investigation.

Regarding the polyfill. The polyfill the extension uses doesn't support AR now. I'm working on the official polyfill integration #3. I haven't looked into the detail yet, but if it supports AR we could start experiments.

**Comment by racheldepaz** [comment]
Hi! Are there any plans to make the emulator also work for Magic Leap?

**Comment by takahirox** [comment]
Thanks for a comment. Unfortunately not specific plan yet. But personally I think we want to do someday.

**Comment by takahirox** [comment]
Discussed the basic idea with @blairmacintyre and I'm going to try to make the prototype maybe in December or later.

**Comment by takahirox** [comment]
FYI: Three.js has an AR example now https://threejs.org/examples/webxr_ar_paint.html

We may start to test on it https://twitter.com/superhoge/status/1199849329550192640

**Comment by takahirox** [comment]
Still WIP and at experimental phase but the prototype https://twitter.com/superhoge/status/1202366436334718976

**Comment by takahirox** [comment]
We added AR initial support. Closing this issue.
