### ISSUE TITLE
Dragging translation plane moves both controllers if their gizmos are overlapped

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/WebXR-emulator-extension#107]
Dragging by any of the translation controls' planes moves both 6 DOF controllers.

**Comment by takahirox** [comment]
You can show/hide the gizmos by clicking the checkboxes left in the panel and solely control. Related #87

Or even if you do that the both controllers move?

**Comment by robertlong** [comment]
The later, I expect dragging the plane handle on the translation gizmo to only move that one controller, not both.

**Comment by takahirox** [comment]
Video from @robertlong 

![ezgif com-optimize](https://user-images.githubusercontent.com/7637832/64652908-d4056c80-d3d9-11e9-98a4-a0ccf7338bcc.gif)

I understand the problem. If two or more gizmos are overlapped and you drag them, all of them are moved. Probably the extension needs to move only the nearest one. We are trying to improve UI/UX in some next releases #106. Until we resolve this problem, please explicitly hide(disable) the gizmos of the devices you don't want to move by clicking the checkboxes.

**Comment by feiss** [comment]
I think we could get rid of this problem by:
1. removing the gizmo checkboxes
3. allowing the user to select a item by clicking on it
2. showing only the gizmo of the current selected object

**Comment by takahirox** [comment]
@feiss Thanks for sharing your idea. That sounds nice. Would you mind if opening a separated issue for the idea? Easier to track the new UI discussion.

**Comment by takahirox** [comment]
@feiss I opened a new issue on your behalf

**Comment by takahirox** [comment]
Closing in favor of #185. You can avoid the issue by selecting only one item.
