### ISSUE TITLE
The extension causes an error in a-frame pages that stops them working

### ISSUE THREAD

**Issue by elbobo** [MozillaReality/WebXR-emulator-extension#108]
Hi,

Great work creating this emulator.

Perhaps you are already aware of this (as you mention it only works on thee.js pages so far) but simply having the extension (without using it) stops pages made in a-frame from working.

Browser: Chrome
Aframe: 0.9.2

I get the following error in my console and the page does not run at all.

<img width="658" alt="wexr_emulator_aframepages" src="https://user-images.githubusercontent.com/5732982/64642578-966b0880-d406-11e9-92e1-f6a3fdefe863.png">

I've had to remove it from my browser so that I can see a-frame pages.

Thanks

**Comment by takahirox** [comment]
Thanks for the report!

That's a known issue. Unfortunately A-Frame seems to use an old WebXR API while the extension uses the new API.

And we are aware of that it's a problem that application can fail if the extension causes an error. So we're trying to automatically disable the extension in such a case.

Related #100 #81

**Comment by takahirox** [comment]
Let me close this issue and let's keep discussing in #100. Regarding A-Frame old WebXR API, please discuss on their repository. Thanks!
