### ISSUE TITLE
XRInputSource handedness shouldn't be null

### ISSUE THREAD

**Issue by mrdoob** [MozillaReality/WebXR-emulator-extension#110]
`handedness` can only be "left", "right", or "none".

<img width="604" alt="Screen Shot 2019-10-06 at 9 45 58 AM" src="https://user-images.githubusercontent.com/97088/66272408-322d4000-e81e-11e9-83ed-0386f9cf9e02.png">

**Comment by mrdoob** [comment]
After https://github.com/mrdoob/three.js/pull/17673 the emulated controllers no longer work.

**Comment by takahirox** [comment]
Thanks for the report! I made PR #111 to resolve the issue.
