### ISSUE TITLE
isSessionSupported is not in latest Chrome build (0.1.1)

### ISSUE THREAD

**Issue by aaaidan** [MozillaReality/WebXR-emulator-extension#118]
When running current version of XR extension on Chrome store (0.1.1), pages that try to use the modern `isSessionSupported` method fail. (e.g. `Uncaught TypeError: navigator.xr.isSessionSupported is not a function`)

I notice that the latest version of the code in repo, `isSessionSupported` has been implemented and `supportsSession` has been deprecated, which is great. Given most XR pages now use `isSessionSupported`, could we have an updated build deployed to the Chrome store?

**Comment by takahirox** [comment]
Hi, thanks for the report!

Yes, unfortunately v0.1.1 doesn't have `navigator.xr.isSessionSupported` yet. We plan to release v0.2.0 maybe in the end of Nov but I'm thinking to release v0.1.2 with `isSessionSupported` before 0.2.0.

But v0.1.2 release may still take time a bit, for the test, review, and so on. So until it's released please manually download and install the extension as [readme describes](https://github.com/MozillaReality/WebXR-emulator-extension#for-development)

**Comment by aaaidan** [comment]
Hi @takahirox, thanks for the info. I can confirm that the dev mode install of the extension works great!

**Comment by takahirox** [comment]
I submitted v0.1.2 to Firefox Add-ons and Chrome web store. On Firefox Add-ons the package has been updated to v0.1.2 but on Chrome web store it seems to take a few days. I'll close this issue once I confirm it's updated on Chrome web store.

**Comment by takahirox** [comment]
Confirmed the package is updated to v0.1.2 on the both stores. Closing this issue.
