### ISSUE TITLE
It seems not working with chrome 78.0.3904.70 (32bits)

### ISSUE THREAD

**Issue by iefreer** [MozillaReality/WebXR-emulator-extension#121]
This would be a very helpful extension for webxr development. but it looks still not working for latest chrome on windows10 platform or did I miss anything there? I installed this extension from chrome extension store, and opened the three.js online example: https://threejs.org/examples/?q=webvr#webvr_ballshooter, and press F12 then choose WEBXR tab, I can see simulator of Oculus Go there, but it doesn't affect the three.js scene at all no matter how I change the rotation, and at the bottom of that example page, there is a tip saying "XR NOT FOUND".

Note that I have already enabled webxr device api and webvr 1.1 flags via chrome://flags.

**Comment by joshmarinacci** [comment]
When did you install the extension? We just pushed out an update.

**Comment by takahirox** [comment]
I've fixed. Until we release the next version at Chrome store, would you please manually download and install the extension as [readme descries](https://github.com/MozillaReality/WebXR-emulator-extension#for-development)?

@joshmarinacci Other users may face this issue, too. I'm thinking to submit v0.1.3 with this bug fix to Firefox/Chrome stores now although we just released v0.1.2 a few days ago. What do you think?

**Comment by joshmarinacci** [comment]
yeah. push out another release.

**Comment by takahirox** [comment]
OK I will.

And I'll close this issue if @iefreer confirms the issue is resolved by manually installing the latest extension code or disabling WebXR API.

**Comment by iefreer** [comment]
@takahirox , cool, the latest extension in development mode is working well now no matter I disable the webxr api or not. 3x!
