### ISSUE TITLE
Big white rectangle appears when selecting device on Chrome

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#146]
![image](https://user-images.githubusercontent.com/7637832/68888971-cff31500-06d0-11ea-9712-d1e427d34cba.png)

This bug exists since even before #144 #145

**Comment by feiss** [comment]
mm doesn't happen in macos.. 

<img width="399" alt="image" src="https://user-images.githubusercontent.com/359872/68979441-d6cb7600-07fd-11ea-96f2-9bad861e5627.png">

Will try on windows when I have one at hand

**Comment by takahirox** [comment]
Thanks for the investigation! It seems this issue may occur only on Windows Chrome. It can be a browser side bug. (Or my side?)

**Comment by takahirox** [comment]
Working fine on my Windows Canary... 

![image](https://user-images.githubusercontent.com/7637832/68980048-2c7b3080-07b4-11ea-8b2f-e31db7972629.png)

**Comment by feiss** [comment]
fine on a win10 + up to date chrome (78.0.3904.97)
![image_2019-11-15_23-30-04](https://user-images.githubusercontent.com/359872/68980220-21e68880-0800-11ea-8560-d44a558974c6.png)

**Comment by feiss** [comment]
maybe a gpu issue? try switching to an integrated gpu, or disabling acceleration on chrome

**Comment by takahirox** [comment]
It's fixed by changing the size and scale to 100% from 250% on Windows display preference.

![image](https://user-images.githubusercontent.com/7637832/68981175-74e81d80-07b7-11ea-8d3b-fb23f6fc0006.png)
![image](https://user-images.githubusercontent.com/7637832/68981197-829da300-07b7-11ea-8810-2c418750689d.png)

I guess Chrome 78 wrongly uses this scale parameter? I'll close this issue once I confirm it's fixed in the next version Chrome. Removing this issue from v0.2.0 so far because the root issue doesn't seem to be in the extension.

Thanks!

**Comment by takahirox** [comment]
Closing because I confirmed this issue has been resolved in Chrome 79
