### ISSUE TITLE
Include Grip Button

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#157]
Similar as how it works right now with the Trigger button, the Grip button should generate the `squeezestart`, `squeeze` and `squeezeend` events as defined by the spec.

**Comment by takahirox** [comment]
Thinking how UI should be. Will we have multiple button dom elements per a controller?

**Comment by fernandojsg** [comment]
I imagine both buttons one next to each other on the same row.
And currently for consistency with the WebXR API I believe they should be called something related to `select` and `squeeze` instead of `trigger` and `grip`.
