### ISSUE TITLE
Remove Gizmo checkboxes and instead selectable items by clicking

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#161]
Suggestion from @feiss https://github.com/MozillaReality/WebXR-emulator-extension/issues/107#issuecomment-554568587

----
I think we could get rid of this problem (#107) by:

1. removing the gizmo checkboxes
2. allowing the user to select a item by clicking on it
3. showing only the gizmo of the current selected object

Apart from solving this issue, the UX would be much nicer and intuitive

Also, this could allow another UX improvement: removing the need of a translate/rotate button:

If the user clicks on an object, the translate gizmo appears on it. And if the user clicks a second time on the same object, the translate gizmo switches to the rotate gizmo. A third click would switch to the translate, and so on.

This operation switching by clicking again on the selected object is used in some programs (Inkscape comes to my mind, but there are a few more).

----

**Comment by takahirox** [comment]
> This operation switching by clicking again on the selected object is used in some programs

Thinking how to distinguish "click" for the operation mode change and "drag" for translating or rotating. If mouseup event is fired right after mousedown event is fired we recognize it's a click to for switching the operation mode?

https://threejs.org/docs/index.html#examples/en/controls/TransformControls

**Comment by feiss** [comment]
can we have both translation and rotation gizmos displayed and useful at the same time? I'm afraid that the previous workflow has very bad discoverability...

**Comment by takahirox** [comment]
That sounds interesting. But can't their gizmos overlap each other and can't be difficult for user to control one of them?
