### ISSUE TITLE
Add presets for headset/controller locations

### ISSUE THREAD

**Issue by connorshea** [MozillaReality/WebXR-emulator-extension#187]
Moving the controllers right now it honestly really annoying, and it'd be nice if there were a dropdown that the user could use to set the headset and controllers in certain positions for testing purposes.

For example:
- Headset looking forward with both controllers in front
- Headset looking down with both controllers pointed down
- Headset looking up with both controllers pointed up

As part of this, being able to rotate the devices in 90 degree horizontal increments would be nice as well, e.g. so you could easily turn around via the inspector.

**Comment by takahirox** [comment]
Thanks for the feedback! The idea sounds interesting to me. Let me think of that in v0.4.0 where I plan to improve the usability. And of course, PR is very welcome anytime.

**Comment by takahirox** [comment]
Note: This idea can be a solution to #156
