### ISSUE TITLE
CORS error can happen if trying to load assets for AR virtual room

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#195]
AR virtual room runs in user application page side, not in devtool panel side. So if we want to load assets and place them in the virtual room, the extension needs to load on user page from somewhere server. That means CORS error can occur depending on the asset server, the user application page server, and the user application configuration.

Related: #193

**Comment by takahirox** [comment]
A solution may be loading room assets in devtool panel side, as we load headset and controllers asset there, and then transferring serialized assets to web page side via port. I'm not sure if serialization and transferring speed is good but I guess worth to try.

**Comment by joshmarinacci** [comment]
It depends on the size of the asset, but the most reliable method would be to have a GLB pre-encoded as a dataURL, which can then be passed to the running webpage. Then the browser only has to do decompression, not compresssion

**Comment by takahirox** [comment]
I succeeded in loading virtual room in WebXR application side.

![image](https://user-images.githubusercontent.com/7637832/75384046-530c3580-5892-11ea-8aa1-1d0f69a9ec1b.png)

The solution I did is to load an asset file as buffer in content-script and send it to the application side with Event. There may be a room to optimize but I close this issue because I found a solution to avoid CORS error.
