### ISSUE TITLE
Disable window.requestAnimationFrame when presenting

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#234]
When using WebXR, if you are in immersive mode window.rAF is not being called. 
I was testing a game and I was dealing with this issue because window.rAF was being called as well as session.rAF.

I suggest to hook window.rAF when the page is loaded and when you are presenting just replace it with a NOP, and replace with the original function back when you exit VR.

**Comment by takahirox** [comment]
Thanks for the report. It may be webxr-polyfill.js side issue. I'll investigate.
