### ISSUE TITLE
Wrong gamepad button configuration for Oculus Touch.

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#237]
Bug report from @checksummaster in https://github.com/MozillaReality/WebXR-emulator-extension/issues/31#issuecomment-619264598

>About button, with oculus touch, I should change some code like that (not so sure why then I don't make a pull request for this)
const BUTTON = {
SELECT: 1,
SQUEEZE: 2
};
before it was 0,1 but 0 is the thump (on the joystick)

**Comment by checksummaster** [comment]
this is from aframe

/**
 * Button indices:
 * 0 - thumbstick (which has separate axismove / thumbstickmoved events)
 * 1 - trigger (with analog value, which goes up to 1)
 * 2 - grip (with analog value, which goes up to 1)
 * 3 - X (left) or A (right)
 * 4 - Y (left) or B (right)
 * 5 - surface (touch only)
 */
var INPUT_MAPPING_WEBVR = {
  left: {
    axes: {thumbstick: [0, 1]},
    buttons: ['thumbstick', 'trigger', 'grip', 'xbutton', 'ybutton', 'surface']
  },
  right: {
    axes: {thumbstick: [0, 1]},
    buttons: ['thumbstick', 'trigger', 'grip', 'abutton', 'bbutton', 'surface']
  }
};

**Comment by jendaz** [comment]
Here is different mapping
https://immersive-web.github.io/webxr-gamepads-module/#xr-standard-gamepad-mapping
index 0 -> Primary trigger, 1 -> Primary squeeze button, 2 -> Primary touchpad, 3 -> Primary thumbstick

And for axes [0, 1] -> Primary touchpad X, Y
[2, 3] -> Primary thumbstick X, Y

**Comment by jendaz** [comment]
I also checked it right now on my Oculus Go in an [example for controller state](https://immersive-web.github.io/webxr-samples/controller-state.html) and when I press the trigger the first button is pressed:
![98031539_10216863943058657_7380806409463529472_o](https://user-images.githubusercontent.com/8435946/82646156-5f472b00-9c14-11ea-8603-d6239e526953.jpg)
But when I pres select button in WebXR extension in Chrome the third button is selected.
<img width="516" alt="Snímek obrazovky 2020-05-22 v 10 02 12" src="https://user-images.githubusercontent.com/8435946/82646192-6ec67400-9c14-11ea-96ac-1de4cc00f21c.png">
<img width="763" alt="Snímek obrazovky 2020-05-22 v 10 02 45" src="https://user-images.githubusercontent.com/8435946/82646195-7128ce00-9c14-11ea-9df7-d6fe69aadf7f.png">


I'm also praying for support of all buttons and axes from the extension.

**Comment by takahirox** [comment]
Thanks for the report and investigation. I'd like to try to resolve in the next release v0.4.0. Also PR is welcome!

**Comment by checksummaster** [comment]
It fixed in this fork. https://github.com/illusioneering/WebXR-emulator-extension (this fork don't have the last modification and not work with aframe 1.2)
This fork also supports more buttons for the quest.

I'm not the one that makes this fork but maybe a pull request should be appropriate.
