### ISSUE TITLE
Show a warning if not using a SecureContext

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#244]
WebXR can't be used without a secure context (https or localhost) but the extension still lets you do it. I think it's fine to let the users use it without requiring a secure context as you are using it mainly for developing, but I believe it's important to show a warning message somewhere if you are not on a secure context (window.isSecureContext) indicating that in any real implementation it won't work as you expect.

**Comment by takahirox** [comment]
Related #197

**Comment by takahirox** [comment]
As #197 I've been thinking whether we should disable the extension in non SecureContext. But yeah the extension should be mainly used for dev purpose and warning sounds reasonable to me. 

I'm thinking to go with the warning in v0.4.0 as you suggested. If anyone has concern about enabling in non SecureContext, please share with us.
