### ISSUE TITLE
Bug - select event should be dispatched before selectend

### ISSUE THREAD

**Issue by De-Panther** [MozillaReality/WebXR-emulator-extension#255]
As written in the working draft https://www.w3.org/TR/webxr/#xrinputsource-interface
```
Queue a task to perform the following steps:
Fire an input source event with name select, frame frame, and source source.
Fire an input source event with name selectend, frame frame, and source source
```

And in https://developer.mozilla.org/en-US/docs/Web/API/XRSession
```
The select event is sent after the selectstart event is sent and immediately before the selectend event is sent.
```

Looking at https://github.com/MozillaReality/WebXR-emulator-extension/blob/dev/polyfill/webxr-polyfill.js
```
                      this[PRIVATE$f].dispatchInputSourceEvent('selectend',  evt.inputSource);
                      this[PRIVATE$f].dispatchInputSourceEvent('select',  evt.inputSource);
```
Those lines should be switched

**Comment by takahirox** [comment]
Thanks for the report! I'll investigate.

**Comment by De-Panther** [comment]
Was fixed and merged in the WebXR Polyfill repo
https://github.com/immersive-web/webxr-polyfill/pull/156
