### ISSUE TITLE
Getting a pose from an offsetReferenceSpace returns returns a pose which is not offset.

### ISSUE THREAD

**Issue by AdaRoseCannon** [MozillaReality/WebXR-emulator-extension#261]
```javascript
const transform = new window.XRRigidTransform(position, orientation);
const offsetReferenceSpace = referenceSpace.getOffsetReferenceSpace(transform);
const pose = frame.getPose(offsetReferenceSpace, localReferenceSpace);
```

`pose.transform` should have the same values as `transform` if the localReferenceSpace and the referenceSpace are the same.

It works as expected in the Oculus browser, in this it comes through at the origin with no rotation.

**Comment by takahirox** [comment]
Thanks for the report. I want to investigate and fix the bug by the next release.

**Comment by AdaRoseCannon** [comment]
Thank you so much for responding so quickly!
