### ISSUE TITLE
Feature Request: Allow for disabling the polyfill 

### ISSUE THREAD

**Issue by gkjohnson** [MozillaReality/WebXR-emulator-extension#264]
Hello! Thank you for the extremely useful extension!

I'd like to request the ability to disable the injection of the WebXR polyfill, which may just mean disabling the extension entirely, so you can test the page in a VR headset without having to uninstall the extension.

I have a VR headset but use the WebXR app to do some basic development first before testing in the real thing. As far as I can tell you can't disable the WebXR extension so once I'm ready to test in the headset I have to remove the extension entirely from Chrome, which is a bit cumbersome.

Thanks again!

**Comment by takahirox** [comment]
Thanks for the feature request. But let me close this issue because it's duplicated with #81. Let's keep the discussion there.

**Comment by gkjohnson** [comment]
Thanks! I'd tried looking around but I missed that issue
