### ISSUE TITLE
WASD/pointerlock controls for AR

### ISSUE THREAD

**Issue by funwithtriangles** [MozillaReality/WebXR-emulator-extension#272]
I think it would be very useful to have something like first person shooter controls for the AR mode.

- The mobile device would be locked directly in front of the camera
- Use WASD to move around the scene
- Use mouse to look around, mobile device is always kept locked to this angle
- Use scroll wheel to move the mobile device further or closer to the camera

Right now it's quite hard to actually test a larger AR scene that involves walking, I feel that familiar controls like these would work quite well

**Comment by takahirox** [comment]
Thanks for the comment. Yeah I have been thinking of improving controls in AR... Let me try some experiment.

**Comment by skar07** [comment]
I agree with @funwithtriangles . It would be really nice to have this. Also, what would be nice is being able to remove the mobile device in order to draw  onto the actual environment from a headset perspective.

**Comment by itsezc** [comment]
@takahirox Any updates on this? Happy to take a stab on a PR
