### ISSUE TITLE
The demos of Babylon.js WebXR don't work

### ISSUE THREAD

**Issue by vaseala** [MozillaReality/WebXR-emulator-extension#281]
[Babylon.js WebXR demo page](https://doc.babylonjs.com/divingDeeper/webXR/webXRDemos)

the demos of this page don't work with 'WebXR-emulator-extension' in firefox and chrome.

**Comment by takahirox** [comment]
Thanks for the problem report. Let me look into it...

**Comment by Zhernet** [comment]
It works well with the released version 4.2.0 but fails with the alpha of version 5 (since 5.0.0-alpha.64, 5.0.0-alpha.63 works fine).
You can revert to 4.2.0 in the playground settings.
