### ISSUE TITLE
How to bring up the controllers programmatically for automatic testing?

### ISSUE THREAD

**Issue by r03ert0** [MozillaReality/WebXR-emulator-extension#284]
I am trying to run automatic tests using WebXR emulator and Puppeteer.
Thus far, I can load the extension and Enter VR (see issue #282). By default, the extension is in Oculus Go/Stereo effect. I can disable the Stereo effect by sending a custom event (see issue #283), and I imagine I can also change the device to Oculus Quest.
However, unless I really go open the devtools and go to the WebXR tab, the controllers are not loaded (once they are loaded, I can move them from the automated tests, take screenshots, etc., etc.).
**Is there a way of bringing the controllers up programmatically?** I think I have tried all custom events from the extension code, but there's maybe something I'm missing?
I'm loading a local version of the WebXR emulator, so I could eventually change the code to make stuff work...

thanks in advance!

**Comment by Utopiah** [comment]
Hi, any progress on the topic a year later? Curious to see how testing could be pushed a bit further than "just" testing if e.g DOM elements are present (if relying on AFrame) of coordinates coherent (if relying on threejs).
