### ISSUE TITLE
enable keyboard shortcuts to map individual emulator controller.

### ISSUE THREAD

**Issue by mingyuen78** [MozillaReality/WebXR-emulator-extension#285]
hi mozilla reality, can we request for this feature as per title. it will help us develop the webxr faster. 
right now is still very tedious to emulate webxr with the emulator, as we have to click individual controllers and then drag them around to control them.

it will be good if we can assign programmable non conflicting shortcut keys to raw, roll, pitch, up, down , left and right for left hand and right hand as well as the headset.

and control button like squeeze and trigger for each left and right. 
this will enable us more seemlessly control the emulated controller.

**Comment by itsezc** [comment]
Duplicate for https://github.com/MozillaReality/WebXR-emulator-extension/issues/272
