### ISSUE TITLE
Chrome Extension Not Working

### ISSUE THREAD

**Issue by wynternight** [MozillaReality/WebXR-emulator-extension#294]
I'm not sure which information will be useful to provide, so please let me know what I can offer to help. For a while, any VR content in the browser would detect the headset and ask for permission to use the headset. It was working as intended.

A few days ago, after a while not using any VR, I noticed that it wouldn't detect it. I uninstalled and reinstalled the extension, but I can't get it to detect a headset. I'm using an Oculus Rift.

It was working just fine in the past, but doesn't work at all now. I've tried VR videos in-browser as well as some of the demos referred to on immersiveweb.dev. I've looked in the developer settings within Chrome but no amount of fiddling appears to solve it.

Thanks in advance. I'm not sure how to troubleshoot this myself.

EDIT: I had to turn off the extension for Chrome to detect a headset, but VR still doesn't load in the browser. At most, the screen will flicker and call up the Oculus app.

**Comment by takahirox** [comment]
Hi, thanks for the problem report.

>  I'm using an Oculus Rift.

To clarify, the extension is for testing WebXR applications on desktop web browsers without any VR devices. I don't have wired VR devices so I have never tried but the extension may not work if WebXR compatible VR headset is connected to the desktop. Probably it's good to try to disconnect the VR device and use the extension.

**Comment by takahirox** [comment]
Closing for now. Please reopen with more detailed information if needed.
