### ISSUE TITLE
Consider using immersive-web/webxr-polyfill

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#3]
https://github.com/immersive-web/webxr-polyfill

The problems are
- ~WebXR API webxr-polyfill follows is old~ (Updated)
- How can I inject webxr-polyfill code to content_script?
- How can the emulator interact with? For example, when button is pressed how can we fire select event of polyfill?

**Comment by takahirox** [comment]
For tracking
- [ ] inputsourceschange event https://github.com/immersive-web/webxr-polyfill/issues/81
- [ ] Proper Event class https://github.com/immersive-web/webxr-polyfill/issues/82

**Comment by joshmarinacci** [comment]
It looks like both of the dependent issues are fixed now.

**Comment by takahirox** [comment]
Yeah thanks for notifying me. So I started to try importing the official webxr-polyfill. I may need to change the design in content script, it may take time.

**Comment by takahirox** [comment]
Closing in favor of #124
