### ISSUE TITLE
Any plans to support AR depth-sensing API?

### ISSUE THREAD

**Issue by mahdavifar2002** [MozillaReality/WebXR-emulator-extension#301]
Specification: https://www.w3.org/TR/webxr-depth-sensing-1/

Currently, the extension does not support depth-sensing and I receive the error "The required feature 'depth-sensing' is not supported" in the console, when trying to test some examples like [this one](https://immersive-web.github.io/webxr-samples/proposals/phone-ar-depth-gpu.html). It would be great if it can be added to the emulator.

**Comment by takahirox** [comment]
PR is very welcome!
