### ISSUE TITLE
Support various type of controller buttons

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#31]
Currently only supports one trigger button. We should support more various type of buttons, for example Oculus Go tough pad(?).

Maybe related to #15

**Comment by checksummaster** [comment]
About button, with oculus touch, I should change some code like that (not so sure why then I don't make a pull request for this)
const BUTTON = {
  SELECT: 1,
  SQUEEZE: 2
};
before it was 0,1 but 0 is the thump (on the joystick)

**Comment by takahirox** [comment]
Thanks for the report. I will look into.

**Comment by takahirox** [comment]
@checksummaster I wanted to separate bug report issue from this feature request issue to track the problem more easily so I opened #237
