### ISSUE TITLE
How to interact with native WebXR API supported by browser

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#34]
Some WebXR API needs to recognize XR device, for example `supportsSession(mode)` checks if device supports the specified mode. Probably need to investigate how emulated XR device can be recognized by WebXR API supported by browser.

**Comment by takahirox** [comment]
Always overriding and I added a note about it to readme.

**Comment by takahirox** [comment]
Maybe I should send the feedback about this issue for test purpose to WebXR API (or somewhere else).

**Comment by takahirox** [comment]
An idea from Kip. We may use WebXR Test API when it's available.

https://github.com/immersive-web/webxr-test-api/blob/master/explainer.md

**Comment by takahirox** [comment]
Another option may be talking to devtool team to see if we can directly embed WebXR emulator extension to browser where it may have access to Testing API, I'm not really sure if Firefox/Chrome accept tho.

**Comment by joshmarinacci** [comment]
That sounds like a giant change. Let's put this on the backburner for now.

**Comment by takahirox** [comment]
Yes, this is far future work.
