### ISSUE TITLE
Easily/Automatically enable/disable the extension

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#81]
For cases where you maybe already have webxr in your system and want to use it instead of the extension. It could be nice to have it available on the pop up menu when clicking the extension icon

**Comment by takahirox** [comment]
Thinking of how to manually disable the extension. Probably the extension wants to store a flag to `storage` indicating whether the extension should be disabled or not. What we want to do may be the extension loads the flag from `storage` at starting and doesn't go forward if the flag indicates "disable".

problem is there is no synchronous `storage` API ever I know. Some WebXR applications, for example Three.js examples, synchronously touches WebXR API when the page is loaded. And there is no way to block user application (ever I know). So it's impossible for the extension to synchronously determine if it should be disabled by the time user application first touches WebXR API.

**Comment by connorshea** [comment]
I'd definitely appreciate this, I was trying to test on my Rift and the controllers weren't being tracked, which was apparently a problem caused by the WebXR emulator extension. It worked once I disabled the extension, but I'd prefer a simpler means of toggling it :)

**Comment by gkjohnson** [comment]
> problem is there is no synchronous storage API ever I know. Some WebXR applications, for example Three.js examples, synchronously touches WebXR API when the page is loaded. And there is no way to block user application (ever I know). So it's impossible for the extension to synchronously determine if it should be disabled by the time user application first touches WebXR API.

Looks like it's still a couple versions out in Chrome, at least, but perhaps [top level await](https://www.chromestatus.com/feature/5767881411264512) could be used to solve this?

**Comment by takahirox** [comment]
Interesting... yeah maybe it can.
