### ISSUE TITLE
Warning about "storage.local" when uploading to the firefox add-ons market

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#98]
![image](https://user-images.githubusercontent.com/782511/64011394-e5b65c80-cb1b-11e9-8dce-6788d74d72ff.png)
![image](https://user-images.githubusercontent.com/782511/64011428-f49d0f00-cb1b-11e9-968d-e29c28932565.png)
![image](https://user-images.githubusercontent.com/782511/64011411-ec44d400-cb1b-11e9-8ed6-b9038280dc12.png)

They link is: https://mzl.la/2hizK4a

**Comment by takahirox** [comment]
We added the extension to the add-on store and made it public. I don't see any problems for now. Closing.
